###
GET http://127.0.0.1:8000/api/features

###
GET http://127.0.0.1:8000/api/features/0

###
GET http://127.0.0.1:8000/api/features/1/image

###
GET http://127.0.0.1:8000/api/images/0

###
POST http://127.0.0.1:8000/api/images/0/features
Content-Type: application/json

{
  "features": [
    {
        "feature_id": 197,
        "activation": 3.0
    }
  ]
}